services:
  - type: web
    name: dracula-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    branch: main
    autoDeploy: false
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: wallets-disk
      mountPath: /app/wallets
      sizeGB: 1
